full name: "Gaute Berge"
full name low: "gaute berge"
first name: "Gaute"
last name: "Berge"
G mail: "gaute.berge@gmail.com"
hot mail: "gaute.berge@hotmail.com"
# work mail: "gaute.berge@bekk.no"
# work domain: "bekk.no"
username: "gauteab"
